<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JCB-MacBook-Pro.local" ignored="7" tests="37" failures="27" timestamp="30 Mar 2020 01:11:59 GMT" time="17.44" errors="0">
  <testcase name="createInvalidOrder400" time="0.417" classname="DeleteAndPost">
    <skipped/>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createInvalidOrder400" time="1.004" classname="DeleteAndPost">
    <skipped/>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createInvalidOrder400" time="0.5" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 200">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 200
at DeleteAndPost.getStatusForPOSTResponse(DeleteAndPost.java:75)
at DeleteAndPost.createInvalidOrder400(DeleteAndPost.java:26)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createInvalidOrder400" time="0.431" classname="DeleteAndPost"/>
  <testcase name="createInvalidOrder400" time="0.439" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 200">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 200
at DeleteAndPost.getStatusForPOSTResponse(DeleteAndPost.java:75)
at DeleteAndPost.createInvalidOrder400(DeleteAndPost.java:26)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createInvalidOrder400" time="0.318" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 200">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 200
at DeleteAndPost.getStatusForPOSTResponse(DeleteAndPost.java:75)
at DeleteAndPost.createInvalidOrder400(DeleteAndPost.java:26)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createInvalidOrder400" time="0.425" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 200">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 200
at DeleteAndPost.getStatusForPOSTResponse(DeleteAndPost.java:75)
at DeleteAndPost.createInvalidOrder400(DeleteAndPost.java:26)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createInvalidOrder400" time="0.454" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 200">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 200
at DeleteAndPost.getStatusForPOSTResponse(DeleteAndPost.java:75)
at DeleteAndPost.createInvalidOrder400(DeleteAndPost.java:26)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createOrder500" time="1.09" classname="DeleteAndPost"/>
  <testcase name="createOrder500" time="0.387" classname="DeleteAndPost"/>
  <testcase name="deleteInvalidIDSupplied" time="0.371" classname="DeleteAndPost">
    <skipped/>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.474" classname="DeleteAndPost">
    <skipped/>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.373" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 404">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 404
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.433" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 404">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 404
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.389" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 404">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 404
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.362" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 404">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 404
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.391" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 404">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 404
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.429" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 200">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 200
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="deleteInvalidIDSupplied" time="0.358" classname="DeleteAndPost">
    <failure type="java.io.IOException" message="Basic criteria failed,was expecting code 400, but got: 404">
      <![CDATA[java.io.IOException: Basic criteria failed,was expecting code 400, but got: 404
at DeleteAndPost.getStatusForDeleteResponse(DeleteAndPost.java:92)
at DeleteAndPost.deleteInvalidIDSupplied(DeleteAndPost.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.954" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid ID supplied] but found [Order not found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid ID supplied] but found [Order not found]
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.496" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid ID supplied] but found [Order not found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid ID supplied] but found [Order not found]
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.379" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: &amp;quot;3.5&amp;quot;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: "3.5"]
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.365" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid ID supplied] but found [Order not found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid ID supplied] but found [Order not found]
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.448" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.355" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.532" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.407" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.454" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.438" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: &amp;quot;3.5&amp;quot;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: "3.5"]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.45" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: &amp;quot;3.5&amp;quot;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: "3.5"]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.41" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.383" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="searchOrderByID400" time="0.451" classname="Get404">
    <failure type="java.lang.AssertionError" message="expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at Get404.getStatusFotGetResponse(Get404.java:45)
at Get404.searchOrderByID400(Get404.java:35)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- searchOrderByID400 -->
  <testcase name="searchOrderByID400" time="0.413" classname="Get404">
    <failure type="java.lang.AssertionError" message="expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at Get404.getStatusFotGetResponse(Get404.java:45)
at Get404.searchOrderByID400(Get404.java:35)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- searchOrderByID400 -->
  <testcase name="searchOrderByID400" time="0.614" classname="Get404">
    <failure type="java.lang.AssertionError" message="expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at Get404.getStatusFotGetResponse(Get404.java:45)
at Get404.searchOrderByID400(Get404.java:35)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- searchOrderByID400 -->
  <testcase name="searchOrderByID400" time="0.419" classname="Get404">
    <failure type="java.lang.AssertionError" message="expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at Get404.getStatusFotGetResponse(Get404.java:45)
at Get404.searchOrderByID400(Get404.java:35)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- searchOrderByID400 -->
  <testcase name="nonExistingUrlReturns404" time="0.34" classname="Get404"/>
  <testcase name="createOrder200" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- createOrder200 -->
  <testcase name="notFoundMessageIsCorrect" time="0.0" classname="BodyTest">
    <ignored/>
  </testcase> <!-- notFoundMessageIsCorrect -->
  <testcase name="returnsCorrectOrderBodyResponse" time="0.0" classname="BodyTest">
    <ignored/>
  </testcase> <!-- returnsCorrectOrderBodyResponse -->
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.0" classname="BodyTest">
    <ignored/>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="deleteOrderNotFound" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- deleteOrderNotFound -->
  <testcase name="deleteIsSuccessful" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- deleteIsSuccessful -->
  <testcase name="searchOrderByID404" time="0.0" classname="Get404">
    <ignored/>
  </testcase> <!-- searchOrderByID404 -->
</testsuite>
